PTA-master/proj1/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from pta import views as pta_views

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'pta/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login'}, name='logout'),
    url(r'^signup/$', pta_views.signup, name='signup'),
    url(r'^abouttheteam/$', pta_views.meettheteam, name='meettheteam'),
    # url(r'^abouttheteam/$', pta_views.AboutTeamView.as_view(), name='meettheteam'),
    url(r'^$', pta_views.homepage, name='homepage'),
    url(r'^edituser$', pta_views.edituser, name='edituser'),
    #url(r'^$', TemplateView.as_view(template_name='pta/home.html'), name='homepage'),
    url(r'^pta/', include('pta.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^homework/$', pta_views.homework, name='homework'),
    url(r'^homework/add$', pta_views.addhomework, name='addhomework'),
    url(r'^todo/$', pta_views.todo, name='todo'),
    url(r'^wishlist/$', pta_views.wishlist, name='wishlist'),
    url(r'^wishlist/add$', pta_views.addwishlist, name='addwishlist'),
]

PTA-master/pta/urls.py
from django.conf.urls import url

from . import views


app_name = 'pta'
urlpatterns = [
#    url(r'^$', views.startpage, name='startpage'),
#url(r'^$', club_views.login_user, name='login'),

    # url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

PTA-master/pta/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from django.contrib.auth.models import AbstractUser, UserManager

# Create your models here.

class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    classinfo = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name

class ParentalUnit(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.user.username

class Homework(models.Model):
    teacher = models.ForeignKey(Teacher, null=False, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    description = models.TextField()
    date_assigned = models.DateField(default=date.today)
    due_date = models.DateField(blank=True, null=True)
    points = models.DecimalField(blank=True, null=True, max_digits=4, decimal_places=1)

    def __str__(self):
        return self.teacher.user.username + ' ' + self.title

    class Meta:
        verbose_name_plural = 'Homework'
        ordering = ['-date_assigned']

class HomeworkGrade(models.Model):
    homework = models.ForeignKey(Homework, null=False, on_delete=models.CASCADE)
    parentalunit = models.ForeignKey(ParentalUnit, null=False, on_delete=models.CASCADE)

    def __str__(self):
        return self.homework.__str__() + ' ' + self.parentalunit.__str__()


class WishlistItem(models.Model):
    description = models.CharField(max_length=150)
    teacher = models.ForeignKey(Teacher, null=False, on_delete=models.CASCADE)
    parentalUnit = models.ForeignKey(ParentalUnit, blank=True, null=True, on_delete=models.SET_NULL)
    received = models.BooleanField(default=False)

    def __str__(self):
        return self.description

class Activity(models.Model):
    description = models.CharField(max_length=150)
    teacher = models.ForeignKey(Teacher, null=False, on_delete=models.CASCADE)
    date_of = models.DateField()
    complete = models.BooleanField(default=False)

    def __str__(self):
        return self.description

    class Meta:
        verbose_name_plural = 'Activities'

class TodoItem(models.Model):
    description = models.TextField()
    teacher = models.ForeignKey(Teacher, null=False, on_delete=models.CASCADE)
    date_assigned = models.DateField(default=date.today, blank=True, null=True)
    due_date = models.DateField(blank=True, null=True)
    # assignedTo = models.ManyToManyField(ParentalUnit, related_name='assigned_to')
    complete = models.BooleanField(default=False)

    def __str__(self):
        return self.description

# class TodoItemAssignedTo(models.Model):
#     item = models.ForeignKey(TodoItem, null=False, on_delete=models.CASCADE)
#     assignedTo = models.ForeignKey(ParentalUnit, null=False, on_delete=models.CASCADE)
#     def __str__(self):
#         return self.item.description

class Message(models.Model):
    teacher = models.ForeignKey(Teacher, null=False, on_delete=models.CASCADE)
    messageBody = models.TextField()
    dateAndTimeOf = models.DateTimeField(auto_now_add=True)
    recipients = models.ManyToManyField(ParentalUnit, related_name='recipients_of')

    def __str__(self):
        return self.messageBody

# class MessageTo(models.Model):
#     message = models.ForeignKey(Message, null=False, on_delete=models.CASCADE)
#     parentalunit = models.ForeignKey(ParentalUnit, null=False, on_delete=models.CASCADE)

class TeamMember(models.Model):
    fullname = models.CharField(max_length=50)
    description = models.CharField(max_length=300)
    imagename = models.CharField(max_length=150)

    def __str__(self):
        return self.fullname

PTA-master/pta/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from .models import Teacher, ParentalUnit, Homework, WishlistItem
from django.db import models
from django.forms import ModelForm
from datetime import date

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    last_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    email = forms.EmailField(max_length=254, help_text='Required. Enter a valid email address.')

    CHOICES = [('', '---------'),('iamaparent', 'I am a parent'), ('iamateacher', 'I am a teacher')]

    typeOfUser = forms.ChoiceField(choices=CHOICES, required=True, label="Role:")

    teacher = forms.ModelChoiceField(queryset=Teacher.objects.all(), required=False, label="My teacher:")

    def clean(self):
        cleaned_data = super(SignUpForm, self).clean()
        cleanedType = cleaned_data.get("typeOfUser")
        teacher = cleaned_data.get("teacher")

        if cleanedType == 'iamaparent' and not teacher:
            print ("iamaparent and not teacher")
            msg = forms.ValidationError("Please select a teacher.")
            self.add_error('teacher', msg)
            # raise forms.ValidationError(
            #     "Please select a teacher."
            # )


    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class AddHomeworkForm(ModelForm):
    # title = forms.CharField(max_length=50, required=True, help_text='Required.')
    # description = forms.CharField(required=True, help_text='Required.')
    # date_assigned = forms.DateField(required=True, default=date.today)
    # date_due = forms.DateField(required=False)
    # points = forms.DecimalField(required=False, max_digits=3, decimal_places=1)

    class Meta:
        model = Homework
        fields = ('title', 'description', 'date_assigned', 'due_date', 'points',)

class AddWishlistForm(ModelForm):
    class Meta:
        model = WishlistItem
        fields = ('id','description',)

class EditUserInfoForm(forms.Form):
    first_name = forms.CharField(max_length=30, required=True, help_text='Required.', error_messages={'required': 'First name is required.'})
    last_name = forms.CharField(max_length=30, required=True, help_text='Required.', error_messages={'required': 'Last name is required.'})
    email = forms.EmailField(max_length=254, help_text='Required. Enter a valid email address.', error_messages={'required': 'Enter a valid email address.'})
    classinfo = forms.CharField(max_length=1000, required=False)


# class UserChooseForm(forms.Form):
#     choose_user = forms.ChoiceField(choices=user_list())
#
#
# class UserEditForm(forms.Form):
#     user_name = forms.CharField(label="Username")
#     password = forms.CharField(label="Password")
#     first_name = forms.CharField(label="First Name")
#     last_name = forms.CharField(label="Last Name", required=False)
#     email = forms.CharField(label="Email address")

PTA-master/pta/templates/pta/addhomework.html
{% extends "pta/base.html" %}

{% block title %}Add homework{% endblock %}

{% block content %}
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}

        <div class="row">
            <div class="col-md-2">
            </div>

            <div class="col-md-8">
                <strong><h2>Add new homework</h2></strong>
                <hr/>

                {% for field in form %}
                    <div class="form-group">
                        <label class="control-label col-sm-2 titillium"
                               for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                        <div class="col-sm-10">
                            {% if field.html_name == "description" %}
                                <textarea class="form-control" rows="5" id="{{ field.id_for_label }}"
                                          name="{{ field.html_name }}"></textarea>
                            {% elif field.html_name == "date_assigned" %}
                                <input type="date" class="form-control" id="{{ field.id_for_label }}"
                                       name="{{ field.html_name }}" value="{{ hwtoday|date:"Y-m-d" }}">
                            {% elif field.html_name == "due_date" %}
                                <input type="date" class="form-control" id="{{ field.id_for_label }}"
                                       name="{{ field.html_name }}">
                            {% elif field.html_name == "points" %}
                                <input type="number" class="form-control" id="{{ field.id_for_label }}"
                                       name="{{ field.html_name }}">
                            {% else %}
                                <input type="text" class="form-control" id="{{ field.id_for_label }}"
                                       name="{{ field.html_name }}">
                            {% endif %}
                            {# {% if field.help_text %}#}
                            {# <span class="help-block">{{ field.help_text|safe }}</span>#}
                            {# {% endif %}#}
                            {% for error in field.errors %}
                                <p style="color: red">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Add</button>
                </div>
            </div>
        </div>


        <div class="col-md-2">
        </div>
    </form>

{% endblock %}

PTA-master/pta/templates/pta/addwishlist.html
{% extends "pta/base.html" %}

{% block title %}Add Wishlist Item{% endblock %}

{% block content %}
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}

        <div class="row">
            <div class="col-md-2">
            </div>

            <div class="col-md-8">
                <strong><h2>Add wishlist item</h2></strong>
                <hr/>

                {% for field in form %}
                    <div class="form-group">
                        <label class="control-label col-sm-2 titillium"
                               for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                        <div class="col-sm-10">
                            {% if field.html_name == "description" %}
                                <textarea class="form-control" rows="5" id="{{ field.id_for_label }}"
                                          name="{{ field.html_name }}"></textarea>
                            {% endif %}
                            {# {% if field.help_text %}#}
                            {# <span class="help-block">{{ field.help_text|safe }}</span>#}
                            {# {% endif %}#}
                            {% for error in field.errors %}
                                <p style="color: red">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Add</button>
                </div>
            </div>
        </div>

        <div class="col-md-2">
        </div>
    </form>

{% endblock %}

PTA-master/pta/templates/pta/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Collaborate! a website for Hidden Valley parents and teachers.{% endblock %}</title>

    <link href="https://fonts.googleapis.com/css?family=Sriracha|Titillium+Web" rel="stylesheet">

    <!-- Latest compiled and minified Bootstrap CSS from remote-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{% static 'pta/styles.css' %}" />

</head>

<body>
<div class="container">
    <header>
        <div id="topHeaderRow">
            <nav class="navbar navbar-inverse">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="navbar-text">
                        {% if user.is_authenticated %}
                            Welcome to Collaborate, {{ user.username }}.
                        {% else %}
                            Welcome to Collaborate.  Please log in.
                        {% endif %}
                    </div>
                    <!--, <a href="#">Login</a> or <a href="#">Create new
                        account</a></div>-->
                </div>
                <div class="collapse navbar-collapse" id="topNavbar">
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-user"></span> Logout</a></li>
                        {% else %}
                            <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-user"></span> Login</a></li>
                            <li><a href="{% url 'signup' %}"><span class="glyphicon glyphicon-user"></span> Create an account</a></li>
                        {% endif %}
                        <!--<li><a href="#"><span class="glyphicon glyphicon-shopping-cart"></span> Shopping Cart</a>
                        </li>
                        <li><a href="#"><span class="glyphicon glyphicon-arrow-right"></span> Checkout</a></li>-->
                    </ul>
                </div>
            </nav>
        </div>
    </header>

    {% if user.is_authenticated %}
        <div id="logoRow">
            <h1>Collaborate!</h1>
            <h4>A website for Sunnydale Elementary School parents and teachers.</h4>
        </div>  <!-- end logoRow -->
    {% endif %}

    <div id="mainNavigationRow">
        <nav class="navbar navbar-default">
            <ul class="nav navbar-nav">
                <li class="{% if nbar == 'home' %}active dropdown{% endif %}">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">User Info
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'homepage' %}">View User Info</a></li>
                        <li><a href="{% url 'edituser' %}">Edit User Info</a></li>
                    </ul>
                </li>
                <li class="{% if nbar == 'homework' %}active{% endif %}"><a href="{% url 'homework' %}">Homework</a></li>
                <li><a href="#">Activities</a></li>
                <li class="{% if nbar == 'todo' %}active{% endif %}"><a href="{% url 'todo' %}">To-Do List</a></li>
                <li class="{% if nbar == 'wishlist' %}active{% endif %}"><a href="{% url 'wishlist' %}">Wish List</a></li>
                <li><a href="#">Message Board</a></li>
                <li class="{% if nbar == 'meettheteam' %}active{% endif %}"><a href="{% url 'meettheteam' %}">Meet the Team</a></li>
            </ul>
        </nav>
    </div>  <!-- end mainNavigationRow -->

    {% block content %}
    {% endblock %}

</div>
</body>
</html>

PTA-master/pta/templates/pta/edituser.html
{% extends "pta/base.html" %}

{% block title %}Edit user{% endblock %}

{% block content %}
    <form class="form-horizontal" method="post">
        {% csrf_token %}


        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-lg" style="margin-left:18px">Save changes</button>
        </div>

        {% for field, errors in form.errors.items %}
            {% for error in errors %}
                <p style="color: red">{{ error }}</p>
            {% endfor %}
        {% endfor %}

        <div class="panel panel-info">
            <div class="panel-heading">
                User
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <label class="control-label col-sm-2" for="id_username">User:</label>
                    <div class="col-sm-6">
                        <input type="text" disabled class="form-control" id="id_username"
                               name="username" value="{{ user }}">
                    </div>
                    <div class="col-sm-4">
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2" for="id_first_name">First Name:</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" id="id_first_name"
                               name="first_name" value="{{ user.first_name }}">
                    </div>
                    <div class="col-sm-4">
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2" for="id_last_name">Last Name:</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" id="id_last_name"
                               name="last_name" value="{{ user.last_name }}">
                    </div>
                    <div class="col-sm-4">
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2" for="id_email">Email Address:</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" id="id_email"
                               name="email" value="{{ user.email }}">
                    </div>
                    <div class="col-sm-4">
                    </div>
                </div>
            </div>
        </div>

        {% if teacher %}
            <div class="panel panel-info">
                <div class="panel-heading">
                    Classroom Info
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="id_classinfo">Class
                            info:</label>
                        <div class="col-sm-6">
                    <textarea class="form-control" rows="6" id="id_classinfo"
                              name="classinfo">{{ classinfo }}</textarea>
                        </div>
                        <div class="col-sm-4">
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    </form>

{% endblock %}

PTA-master/pta/templates/pta/home.html
{% extends "pta/base.html" %}

{% block title %}Collaborate! dashboard{% endblock %}

{% block content %}
    <div class="panel panel-info">
        <div class="panel-heading">
            User
        </div>
        <div class="panel-body">
            <p>Username: {{ user }}</p>
            <p>First Name: {{ user.first_name }}</p>
            <p>Last Name: {{ user.last_name }}</p>
            <p>Email Address: {{ user.email }}</p>
            <p><a href="{% url 'edituser' %}">Edit User Info</a></p>
        </div>
    </div>

    <div class="panel panel-info">
        <div class="panel-heading">
            Classroom Info
        </div>
        <div class="panel-body">
            {% if teacher %}
                <p>Teacher's Name: {{ teacher }}</p>
                <p>Teacher's Username: {{ teacher.user }}</p>
                <hr/>
                <p>{{ teacher.classinfo }}</p>
            {% else %}
                <p>No classroom info to display for this user.</p>
            {% endif %}
        </div>
    </div>

    {% if parentlist %}
        <div class="panel panel-info">
            <div class="panel-heading">
                Classlist
            </div>
            <div class="panel-body">
                <table class="table">
                    <thead>
                    <tr>
                        <th>username</th>
                        <th>First name</th>
                        <th>Last name</th>
                        <th>Email</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for par in parentlist %}
                        <tr>
                            <td>{{ par }}</td>
                            <td>{{ par.user.first_name }}</td>
                            <td>{{ par.user.last_name }}</td>
                            <td>{{ par.user.email }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endif %}

{% endblock %}

PTA-master/pta/templates/pta/homework.html
{% extends "pta/base.html" %}

{% load staticfiles %}

{% block title %}Homework{% endblock %}

{% block content %}

    {% if teacher %}
        <a href="{% url 'addhomework' %}" class="btn btn-primary btn-lg" role="button">Add homework</a>
    {% endif %}

    {% if homeworkList %}
        <table class="table">
            <thead>
            <tr>
                <th>title</th>
                <th>description</th>
                <th>date assigned</th>
                <th>date due</th>
                <th>points</th>
            </tr>
            </thead>
            <tbody>
            {% for hw in homeworkList %}
                <tr>
                    <td>{{ hw.title }}</td>
                    <td>{{ hw.description }}</td>
                    <td>{{ hw.date_assigned }}</td>
                    <td>{{ hw.due_date }}</td>
                    <td>{{ hw.points }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        There is no homework to display for this user.
    {% endif %}

{% endblock %}

PTA-master/pta/templates/pta/index.html
{% extends "pta/base.html" %}

{% load staticfiles %}

{% block content %}
<div class="container">
    <header>

        <div id="topHeaderRow">
            <nav class="navbar navbar-inverse">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="navbar-text">Welcome to Collaborate.</div>
                    <!--, <a href="#">Login</a> or <a href="#">Create new
                        account</a></div>-->
                </div>
                <div class="collapse navbar-collapse" id="topNavbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a data-toggle="modal" href="#loginModal"><span class="glyphicon glyphicon-user"></span> Login</a></li>
                        <li><a data-toggle="modal" href="#registerModal"><span class="glyphicon glyphicon-user"></span> Register</a></li>
                        <!--<li><a href="#"><span class="glyphicon glyphicon-shopping-cart"></span> Shopping Cart</a>
                        </li>
                        <li><a href="#"><span class="glyphicon glyphicon-arrow-right"></span> Checkout</a></li>-->
                    </ul>
                </div>
            </nav>
        </div>

        <div id="logoRow">
            <!--
            <form action="http://www.randyconnolly.com/tests/process.php" class="form-inline">
                <div class='btn-toolbar pull-right'>
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search" name="search">
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <i class="glyphicon glyphicon-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
            -->
            <h1>Collaborate!</h1>
            <h4>A website for Sunnydale Elementary School parents and teachers.</h4>
        </div>  <!-- end logoRow -->

        <!--
        <div id="mainNavigationRow">
            <nav class="navbar navbar-default">
                <ul class="nav navbar-nav">
                    <li><a href="assign2-index.html">Home</a></li>
                    <li class="active"><a href="assign2-about.html">About Us</a></li>
                    <li><a href="assign2-work.html">Art Works</a></li>
                    <li><a href="assign2-artists.html">Artists</a></li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Specials
                            <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Special 1</a></li>
                            <li><a href="#">Special 2</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>  -->

    </header>

    <div class="jumbotron">
        <!--
        <h3>About Us</h3>
        <p>This assignment was created by <em>Suat Iskender</em>.</p>
        <p>It was created for CS4720 at Kennesaw State University.</p>
        <button type="button" class="btn btn-primary btn-lg">Learn more</button>
        -->
    </div>

    <!-- login Modal -->
    <div id="loginModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Login</h4>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="username">Username:</label>
                            <input type="text" class="form-control" id="username" placeholder="Enter username...">
                        </div>
                        <div class="form-group">
                            <label for="pwd">Password:</label>
                            <input type="password" class="form-control" id="pwd" placeholder="Enter password...">
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">Login</button>
                        </div>
                        <div class="form-group text-right">
                            <a href="#">Forgot Password?</a>
                        </div>
                    </form>
                </div>
                <!--
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>-->
            </div>

        </div>
    </div>

    <!-- register Modal -->
    <div id="registerModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Modal Header</h4>
                </div>
                <div class="modal-body">
                    <p>Some text in the modal.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>


</div>

{% endblock %}

PTA-master/pta/templates/pta/meettheteam.html
{% extends "pta/base.html" %}

{% load staticfiles %}

{% block title %}Meet the Team{% endblock %}

{% block content %}
    {% for person in teammember_list %}
    <div class="row">
        <div class="col-md-3">
        </div>
        <div class="col-md-6">
            <div class="thumbnail">
                <a href="#"><img src="/static/pta/{{ person.imagename }}" class="img-thumbnail" width="200" height="200"
                                 alt="pic of {{ person.fullname }}"></a>
                <div class="caption text-center">
                    <p><strong>{{ person.fullname }}</strong></p>
                </div>
                <div class="caption text-justify">
                    <p>{{ person.description }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
        </div>
    </div>
    {% endfor %}

{% endblock %}

PTA-master/pta/templates/pta/todo.html
{% extends "pta/base.html" %}

{% load staticfiles %}

{% block title %}Todo{% endblock %}

{% block content %}
{% endblock %}